package jframezzzz69;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author linzcar20
 */
public class MyJFrame extends javax.swing.JFrame {

    private ArrayList<Destination> destinations = new ArrayList<Destination>();
    private ArrayList<Airport> ap = new ArrayList<Airport>();
    private String fileName;

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame(ArrayList<Airport> ap) {
        this.ap = ap;
        initComponents();
        outList.setEnabled(false);
        output2.setEditable(false);
        createPanel.setVisible(false);
        mainPanel.setVisible(false);
        savePanel.setVisible(false);
        output.setEditable(false);
        apChoosePanel.setVisible(false);
        editPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apChoosePanel = new javax.swing.JPanel();
        apNames = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        chooseB = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        openTrip1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();
        dest = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        ppl = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        saveTripButton = new javax.swing.JButton();
        openTrip = new javax.swing.JButton();
        clearTrip = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outList = new javax.swing.JList<String>();
        editButton = new javax.swing.JButton();
        quickSave = new javax.swing.JButton();
        savePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tripName = new javax.swing.JTextField();
        saveButton2 = new javax.swing.JButton();
        createPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        startLocation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        startPeople = new javax.swing.JComboBox<String>();
        startButton = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outList2 = new javax.swing.JList();
        output2 = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        changeLocation = new javax.swing.JButton();
        submitEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trip  Creator");

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel7.setText("Choose Airport");

        chooseB.setText("Choose");
        chooseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout apChoosePanelLayout = new javax.swing.GroupLayout(apChoosePanel);
        apChoosePanel.setLayout(apChoosePanelLayout);
        apChoosePanelLayout.setHorizontalGroup(
            apChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apChoosePanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(apChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apChoosePanelLayout.createSequentialGroup()
                        .addComponent(apNames, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, apChoosePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(222, 222, 222))))
            .addGroup(apChoosePanelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(chooseB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        apChoosePanelLayout.setVerticalGroup(
            apChoosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apChoosePanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(apNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(chooseB)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel4.setText("Welcome to TripCreator");

        create.setText("Create New Trip");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });

        openTrip1.setText("Open Trip");
        openTrip1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openTrip1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(openTrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openTrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jLabel1.setText("Enter your destination");

        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        ppl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5+" }));
        ppl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pplActionPerformed(evt);
            }
        });

        jLabel2.setText("Amount of people");

        saveTripButton.setText("Save Trip");
        saveTripButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveTripButtonMouseClicked(evt);
            }
        });

        openTrip.setText("Open Trip");
        openTrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openTripMouseClicked(evt);
            }
        });

        clearTrip.setText("Clear Trip");
        clearTrip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearTripMouseClicked(evt);
            }
        });

        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        outList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        outList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        outList.setToolTipText("");
        outList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(outList);

        editButton.setText("Edit");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });

        quickSave.setText("Quicksave");
        quickSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quickSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ppl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(saveTripButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openTrip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quickSave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clearTrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveTripButton)
                    .addComponent(openTrip)
                    .addComponent(quickSave))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(clearTrip))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(editButton))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel3.setText("Trip Name");

        saveButton2.setText("Save");
        saveButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savePanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(tripName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savePanelLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(saveButton2)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(savePanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savePanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tripName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveButton2)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jLabel5.setText("Where would you like to start?");

        jLabel6.setText("How Many People?");

        startPeople.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5+" }));

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startLocation)
                    .addComponent(jLabel6)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startPeople, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(startLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(startPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(startButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(outList2);

        doneButton.setText("Done");
        doneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneButtonMouseClicked(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        changeLocation.setText("Change Location");
        changeLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeLocationMouseClicked(evt);
            }
        });

        submitEdit.setText("Submit");

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeLocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doneButton))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(output2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitEdit)))
                .addContainerGap())
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeButton)
                        .addComponent(changeLocation)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(output2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitEdit))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(apChoosePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(apChoosePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openTrip1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTrip1MouseClicked
        // TODO add your handling code here:
        openButtons();
        sidePanel.setVisible(false);
    }//GEN-LAST:event_openTrip1MouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        // TODO add your handling code here:
        sidePanel.setVisible(false);
        createPanel.setVisible(true);
    }//GEN-LAST:event_createMouseClicked

    private void saveButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButton2MouseClicked
        saves();
    }//GEN-LAST:event_saveButton2MouseClicked

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        ArrayList<Integer> ind = exist(startLocation.getText());
        if (ind.size() == 1) {
            destinations.add(new Destination(capitalize(startLocation.getText()), ap.get(ind.get(0)).getName(), startPeople.getSelectedIndex() + 1));
            createPanel.setVisible(false);
            mainPanel.setVisible(true);
        } else if (startLocation.getText().equals("")) {
            System.out.println("Enter a city");
        } else if (!ind.isEmpty()) {
            apChoose(ind);
        } else {
            System.out.println("Error: City Doesn't Exist");
        }
        view();
    }//GEN-LAST:event_startButtonMouseClicked

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed

    }//GEN-LAST:event_outputActionPerformed

    private void clearTripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearTripMouseClicked
        // TODO add your handling code here:
        destinations.clear();
        view();
    }//GEN-LAST:event_clearTripMouseClicked

    private void openTripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTripMouseClicked
        // TODO add your handling code here:
        openButtons();
    }//GEN-LAST:event_openTripMouseClicked

    private void saveTripButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveTripButtonMouseClicked
        mainPanel.setVisible(false);
        savePanel.setVisible(true);
    }//GEN-LAST:event_saveTripButtonMouseClicked

    private void pplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pplActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling code here:
        ArrayList<Integer> ind = exist(dest.getText());
        if (ind.size() == 1) {
            destinations.add(new Destination(capitalize(dest.getText()), ap.get(ind.get(0)).getName(), ppl.getSelectedIndex() + 1));
        } else if (dest.getText().equals("")) {
            output.setText("Enter a City");
        } else if (destinations.isEmpty() && !ind.isEmpty()) {
            apChoose(ind);
        } else if (!destinations.get(destinations.size() - 1).getLocation().equals(dest.getText()) && !ind.isEmpty()) {
            apChoose(ind);
        } else {
            if (!ind.isEmpty()) {
                output.setText("You are already in this city");
            } else {
                output.setText("City does not exist");
            }
        }
        dest.setText("");
        view();
    }//GEN-LAST:event_addButtonMouseClicked

    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destActionPerformed

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
        editPanel.setVisible(true);
        mainPanel.setVisible(false);
        view();
    }//GEN-LAST:event_editButtonMouseClicked

    private void outListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outListMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_outListMouseClicked

    private void chooseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseBMouseClicked
        // TODO add your handling code here:
        String s = (String) apNames.getSelectedItem();
        String city = null;
        for (int i = 0; i < ap.size(); i++) {
            if (ap.get(i).getName().equals(s)) {
                city = ap.get(i).getCity();
                break;
            }
        }
        destinations.add(new Destination(city, s, ppl.getSelectedIndex() + 1));
        mainPanel.setVisible(true);
        apChoosePanel.setVisible(false);
        apNames.removeAllItems();
        view();
    }//GEN-LAST:event_chooseBMouseClicked

    private void doneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneButtonMouseClicked
        // TODO add your handling code here:
        editPanel.setVisible(false);
        mainPanel.setVisible(true);
        view();
    }//GEN-LAST:event_doneButtonMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        // TODO add your handling code here:
        int index = outList2.getSelectedIndex();
        if (index == -1) {
            output2.setText("Select an item to remove");
        } else {
            destinations.remove(index);
        }
        view();
    }//GEN-LAST:event_removeButtonMouseClicked

    private void quickSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickSaveMouseClicked
        // TODO add your handling code here:
        saves();
    }//GEN-LAST:event_quickSaveMouseClicked

    private void changeLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLocationMouseClicked
        // TODO add your handling code here:
        int index = outList2.getSelectedIndex();
        if (index == -1) {
            output2.setText("Select an item to change");
        } else {
            output2.setEditable(true);
            output2.setText("Enter new location here");
        }
        view();
    }//GEN-LAST:event_changeLocationMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel apChoosePanel;
    private javax.swing.JComboBox apNames;
    private javax.swing.JButton changeLocation;
    private javax.swing.JButton chooseB;
    private javax.swing.JButton clearTrip;
    private javax.swing.JButton create;
    private javax.swing.JPanel createPanel;
    private javax.swing.JTextField dest;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel editPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton openTrip;
    private javax.swing.JButton openTrip1;
    private javax.swing.JList<String> outList;
    private javax.swing.JList outList2;
    private javax.swing.JTextField output;
    private javax.swing.JTextField output2;
    private javax.swing.JComboBox ppl;
    private javax.swing.JButton quickSave;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton saveButton2;
    private javax.swing.JPanel savePanel;
    private javax.swing.JButton saveTripButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField startLocation;
    private javax.swing.JComboBox<String> startPeople;
    private javax.swing.JButton submitEdit;
    private javax.swing.JTextField tripName;
    // End of variables declaration//GEN-END:variables

    public String capitalize(String s) {
        Scanner sc = new Scanner(s);
        String temp;
        s = "";
        while (sc.hasNext()) {
            temp = sc.next();
            s += " " + temp.substring(0, 1).toUpperCase() + temp.substring(1).toLowerCase();
        }
        return s.trim();
    }

    private void openButtons() {
        JFileChooser j = new JFileChooser();
        j.setCurrentDirectory(new File(j.getCurrentDirectory() + "\\NetBeansProjects\\JFRAMEZZZZ69\\Trips"));
        int selection = j.showOpenDialog(null);
        if (selection == 0) {
            File selected = j.getSelectedFile();
            try {
                Scanner carl = new Scanner(selected);
                destinations.clear();
                String pl = "";
                while (carl.hasNextLine()) {
                    if (carl.hasNext()) {
                        while (!carl.hasNextInt()) {
                            pl += carl.next() + " ";
                        }
                        int p = carl.nextInt();
                        destinations.add(new Destination(pl.trim(), carl.nextLine(), p));
                        pl = "";
                    } else {
                        break;
                    }
                }
                output.setText("Opened");
            } catch (FileNotFoundException ex) {
                output.setText("ERROR");
                Logger.getLogger(MyJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        fileName = j.getSelectedFile().getName();
        mainPanel.setVisible(true);
        view();
    }

    public ArrayList<Integer> exist(String s) {
        ArrayList<Integer> ind = new ArrayList<Integer>();
        for (int i = 0; i < ap.size(); i++) {
            Airport a = ap.get(i);
            if (a.getCity().toLowerCase().equals(s.toLowerCase())) {
                ind.add(i);
            } else if (a.getCountry().toLowerCase().equals(s.toLowerCase())) {
                ind.add(i);
            }
        }
        return ind;
    }

    public void apChoose(ArrayList<Integer> ind) {
        for (int i = 0; i < ind.size(); i++) {
            apNames.addItem(ap.get(ind.get(i)).getName());
        }
        apChoosePanel.setVisible(true);
        mainPanel.setVisible(false);
        if (createPanel.isVisible()) {
            createPanel.setVisible(false);
        }
    }

    public void view() {
        String[] dests = new String[destinations.size()];
        for (int i = 0; i < destinations.size(); i++) {
            dests[i] = (i + 1) + " - " + destinations.get(i).toString();
        }
        outList2.setListData(dests);
        outList.setListData(dests);
    }

    public void saves() {
        PrintStream p = null;
        JFileChooser path = new JFileChooser();
        if (fileName.isEmpty()) {
            fileName = tripName.getText().trim() + ".txt";
        } 
        try {
            // TODO add your handling code here:
            p = new PrintStream(new File(path.getCurrentDirectory() + "\\NetBeansProjects\\JFRAMEZZZZ69\\Trips" + File.separator + fileName));
            tripName.setText("");
            for (int i = destinations.size(); i > 0; i--) {
                p.println(destinations.get(destinations.size() - i).getLocation() + " " + destinations.get(destinations.size() - i).getNumPeople() + " " + destinations.get(destinations.size() - i).getAirport());
            }
            System.out.println((char) 27 + "[32mGreat Success!" + (char) 27 + "[0m");
            output.setText("Great Success");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MyJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            p.close();
        }
        fileName = tripName.getText();
        savePanel.setVisible(false);
        mainPanel.setVisible(true);
    }

}
